Tracked the throttling policy ID - Reviewed code.
adobe-apiplatform/api-gateway-request-tracking pull request #13
Opened 2017-08-07 12:02 UTC by andralungu

Addressed the code review comments from https://github.com/adobe-apiplatform/api-gateway-request-tracking/pull/12#issuecomment-320639708

@cristianconstantin, @atrifan ping.

2017-08-07 13:23 UTC, atrifan requested changes

2017-08-07 13:23 UTC, atrifan commented on src/lua/api-gateway/tracking/validator/blockingRulesValidator.lua
> +    ngx.var.blocked_by = math.floor(tonumber(blocking_rule.id/10000));
it's tonumber(blocking_rule.id)/10000

2017-08-07 13:23 UTC, atrifan commented on src/lua/api-gateway/tracking/validator/delayingRulesValidator.lua
> +    ngx.var.delayed_by = math.floor(tonumber(delaying_rule.id/10000));
tonumber(delaying_rule.id)/10000

2017-08-07 13:23 UTC, atrifan commented on src/lua/api-gateway/tracking/validator/rewritingRulesValidator.lua
> +    ngx.var.rewritten_by = math.floor(tonumber(rewrite_rule.id/10000))
tonumber(rewrite_rule.id)/10000

2017-08-08 08:33 UTC, andralungu commented
```10.76.208.236 [08/Aug/2017:08:33:00 +0000] host="throttling-test-dev.adobe.io" request="GET /hello HTTP/1.1" api_key="free_api_key" status=200 bbs=14 rt=5.500 hr="-" ua="-" xfwdf="193.105.140.131" upadd="-" upstat=- uprt="-" sid="it" sname="it" region="ue1" reqid="DaLJTQGNNaiZC5nLk0Nitc10cdfLcl14" delayed="5.5" delayed_by="47" blocked_by="" rewritten_by=""``` tested on dev.

2017-08-08 08:33 UTC, merged